# Generated by Django 5.0.2 on 2024-04-20 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FonoTCSApp', '0005_appuser_age_appuser_conclusionyear_appuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('if_situation', models.TextField()),
                ('and_situation', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('option_a_weight', models.IntegerField()),
                ('option_b_weight', models.IntegerField()),
                ('option_c_weight', models.IntegerField()),
                ('option_d_weight', models.IntegerField()),
                ('option_e_weight', models.IntegerField()),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FonoTCSApp.cases')),
            ],
        ),
    ]
