# Generated by Django 5.0.2 on 2024-05-04 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FonoTCSApp', '0007_alter_questions_option_a_weight_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('highestDegree', models.CharField(default='', max_length=50)),
                ('conclusionYear', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('classId', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='conclusionYear',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='highestDegree',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
