# Generated by Django 5.0.2 on 2024-05-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FonoTCSApp', '0008_student_teacher_remove_appuser_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.FloatField(default=0.0),
        ),
    ]
