# Generated by Django 5.0.2 on 2024-05-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FonoTCSApp', '0009_student_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
    ]
