# Generated by Django 5.0.2 on 2024-05-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FonoTCSApp', '0011_remove_teacher_classid_classes_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
